name: Continuous Integration
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Run Linter
        run: npm run lint
      - name: Generate JSDoc Documentation
        run: npm run jsdoc
      - name: Upload coverage reports to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
