name: JSDoc generation

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: JSDoc Generation
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./docs
          config_file: jsdoc_config.json
          front_page: README.md
      - name: Commit JSDoc
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add . && git commit -m "Documentation Generated")
          git push
