name: Release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: npx --package=node@22 -c semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
